package collector

import (
	"context"
	"log"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	"github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	"github.com/prometheus/client_golang/prometheus"
)

// 1 - Read Collector Interface
type ALBCollector struct {
	cwClient  *cloudwatch.Client
	elbClient *elasticloadbalancingv2.Client

	// 2 - Metrics we want to Add
	// https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html
	//
	// Traffic
	requestCount      *prometheus.Desc
	activeConnections *prometheus.Desc
	// Latency
	targetResponseTime *prometheus.Desc
	// Errors
	httpCodeELB5xx    *prometheus.Desc
	httpCodeTarget4xx *prometheus.Desc
	httpCodeTarget5xx *prometheus.Desc
	// Health
	healthyHostCount   *prometheus.Desc
	unhealthyHostCount *prometheus.Desc
}

// 3 - Constructor function that initialize the descriptors
func NewALBCollector(cwClient *cloudwatch.Client, elbClient *elasticloadbalancingv2.Client) *ALBCollector {
	return &ALBCollector{
		cwClient:  cwClient,
		elbClient: elbClient,
		// Constructor - Name Conventions to name metrics
		requestCount: prometheus.NewDesc(
			"alb_request_count_total",
			"Total number of requests",
			[]string{"load_balancer"},
			nil,
		),
		activeConnections: prometheus.NewDesc(
			"alb_active_connections",
			"Active connections",
			[]string{"load_balancer"},
			nil,
		),
		targetResponseTime: prometheus.NewDesc(
			"alb_target_response_time",
			"Time elapsed. Time until response headers",
			[]string{"load_balancer"},
			nil,
		),
		httpCodeELB5xx: prometheus.NewDesc(
			"alb_http_code_elb_5xx",
			"The number of HTTP 5xx server error codes",
			[]string{"load_balancer"},
			nil,
		),
		httpCodeTarget4xx: prometheus.NewDesc(
			"alb_http_code_target_4xx",
			"The number of HTTP generated by the targets",
			[]string{"load_balancer"},
			nil,
		),
		httpCodeTarget5xx: prometheus.NewDesc(
			"alb_http_code_target_5xx",
			"The number of HTTP generated by the targets",
			[]string{"load_balancer"},
			nil,
		),
		healthyHostCount: prometheus.NewDesc(
			"alb_healthy_host_count",
			"The number of targets that are healthy",
			[]string{"load_balancer"},
			nil,
		),
		unhealthyHostCount: prometheus.NewDesc(
			"alb_unhealthy_host_count",
			"The number of targets that are unhealthy",
			[]string{"load_balancer"},
			nil,
		),
	}
}

// 4 - Describe() method send all prometheus.Desc to channel
func (c *ALBCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- c.requestCount
	ch <- c.activeConnections
	ch <- c.targetResponseTime
	ch <- c.httpCodeELB5xx
	ch <- c.httpCodeTarget4xx
	ch <- c.httpCodeTarget5xx
	ch <- c.healthyHostCount
	ch <- c.unhealthyHostCount
}

// 5 - collect() method - CloudWatch API calls
func (c *ALBCollector) Collect(ch chan<- prometheus.Metric) {
	ctx := context.TODO()

	// 5.1 - Get ALB
	albOutput, err := c.elbClient.DescribeLoadBalancers(ctx, &elasticloadbalancingv2.DescribeLoadBalancersInput{
		Names: []string{"thanasis-LB"},
	})
	if err != nil {
		log.Printf("error describing load balancer: %v", err)
		return
	}

	// Get ARN
	fullARN := *albOutput.LoadBalancers[0].LoadBalancerArn
	//
	parts := strings.SplitAfter(fullARN, "loadbalancer/")
	albARN := parts[1]

	// 5.2 - GetMetricStatistics for every metric
	requestOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("RequestCount"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticSum},
	})
	if err != nil {
		log.Printf("error getting RequestCount: %v", err)
		return
	}

	activeConnOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("ActiveConnectionCount"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticSum},
	})
	if err != nil {
		log.Printf("error getting activeConnOutput: %v", err)
		return
	}

	responseTimeOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("TargetResponseTime"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticAverage},
	})
	if err != nil {
		log.Printf("error getting responseTimeOutput: %v", err)
		return
	}

	elb5xxOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("HTTPCode_ELB_5XX_Count"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticSum},
	})
	if err != nil {
		log.Printf("error getting elb5xxOutput: %v", err)
		return
	}

	target4xxOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("HTTPCode_Target_4XX_Count"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticSum},
	})
	if err != nil {
		log.Printf("error getting target4xxOutput: %v", err)
		return
	}

	target5xxOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("HTTPCode_Target_5XX_Count"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticSum},
	})
	if err != nil {
		log.Printf("error getting target5xxOutput: %v", err)
		return
	}

	healthyOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("HealthyHostCount"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticAverage},
	})
	if err != nil {
		log.Printf("error getting healthyOutput: %v", err)
		return
	}

	unhealthyOutput, err := c.cwClient.GetMetricStatistics(ctx, &cloudwatch.GetMetricStatisticsInput{
		Namespace:  aws.String("AWS/ApplicationELB"),
		MetricName: aws.String("UnhealthyHostCount"),
		Dimensions: []types.Dimension{
			{
				Name:  aws.String("LoadBalancer"),
				Value: aws.String(albARN),
			},
		},
		StartTime:  aws.Time(time.Now().Add(-5 * time.Minute)),
		EndTime:    aws.Time(time.Now()),
		Period:     aws.Int32(300),
		Statistics: []types.Statistic{types.StatisticAverage},
	})
	if err != nil {
		log.Printf("error getting unhealthyOutput: %v", err)
		return
	}

	// Send to Prometheus - MustNewConstMetric
	// 5.3 - Send metrics to Prometheus
	if len(requestOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.requestCount, prometheus.CounterValue, *requestOutput.Datapoints[0].Sum, albARN)
	}
	if len(activeConnOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.activeConnections, prometheus.CounterValue, *activeConnOutput.Datapoints[0].Sum, albARN)
	}
	if len(responseTimeOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.targetResponseTime, prometheus.GaugeValue, *responseTimeOutput.Datapoints[0].Average, albARN)
	}
	if len(elb5xxOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.httpCodeELB5xx, prometheus.CounterValue, *elb5xxOutput.Datapoints[0].Sum, albARN)
	}
	if len(target4xxOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.httpCodeTarget4xx, prometheus.CounterValue, *target4xxOutput.Datapoints[0].Sum, albARN)
	}
	if len(target5xxOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.httpCodeTarget5xx, prometheus.CounterValue, *target5xxOutput.Datapoints[0].Sum, albARN)
	}
	if len(healthyOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.healthyHostCount, prometheus.GaugeValue, *healthyOutput.Datapoints[0].Average, albARN)
	}
	if len(unhealthyOutput.Datapoints) > 0 {
		ch <- prometheus.MustNewConstMetric(c.unhealthyHostCount, prometheus.GaugeValue, *unhealthyOutput.Datapoints[0].Average, albARN)
	}
}
